// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: CalculateSimpleIntrestPb.proto

package CalculateSI

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalculateSIRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Principle float32 `protobuf:"fixed32,1,opt,name=principle,proto3" json:"principle,omitempty"`
	Rate      float32 `protobuf:"fixed32,2,opt,name=rate,proto3" json:"rate,omitempty"`
	Time      float32 `protobuf:"fixed32,3,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *CalculateSIRequest) Reset() {
	*x = CalculateSIRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CalculateSimpleIntrestPb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculateSIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateSIRequest) ProtoMessage() {}

func (x *CalculateSIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CalculateSimpleIntrestPb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateSIRequest.ProtoReflect.Descriptor instead.
func (*CalculateSIRequest) Descriptor() ([]byte, []int) {
	return file_CalculateSimpleIntrestPb_proto_rawDescGZIP(), []int{0}
}

func (x *CalculateSIRequest) GetPrinciple() float32 {
	if x != nil {
		return x.Principle
	}
	return 0
}

func (x *CalculateSIRequest) GetRate() float32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *CalculateSIRequest) GetTime() float32 {
	if x != nil {
		return x.Time
	}
	return 0
}

type CalculateSIResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Si  float32 `protobuf:"fixed32,1,opt,name=Si,proto3" json:"Si,omitempty"`
	Tot float32 `protobuf:"fixed32,2,opt,name=tot,proto3" json:"tot,omitempty"`
}

func (x *CalculateSIResponse) Reset() {
	*x = CalculateSIResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CalculateSimpleIntrestPb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculateSIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateSIResponse) ProtoMessage() {}

func (x *CalculateSIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_CalculateSimpleIntrestPb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateSIResponse.ProtoReflect.Descriptor instead.
func (*CalculateSIResponse) Descriptor() ([]byte, []int) {
	return file_CalculateSimpleIntrestPb_proto_rawDescGZIP(), []int{1}
}

func (x *CalculateSIResponse) GetSi() float32 {
	if x != nil {
		return x.Si
	}
	return 0
}

func (x *CalculateSIResponse) GetTot() float32 {
	if x != nil {
		return x.Tot
	}
	return 0
}

var File_CalculateSimpleIntrestPb_proto protoreflect.FileDescriptor

var file_CalculateSimpleIntrestPb_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x69, 0x6d, 0x70, 0x6c,
	0x65, 0x49, 0x6e, 0x74, 0x72, 0x65, 0x73, 0x74, 0x50, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0b, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x49, 0x22, 0x5a, 0x0a,
	0x12, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x49, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x70, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x6c,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x04, 0x72, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x37, 0x0a, 0x13, 0x43, 0x61, 0x6c,
	0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x49, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x53, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x53, 0x69,
	0x12, 0x10, 0x0a, 0x03, 0x74, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x74,
	0x6f, 0x74, 0x32, 0xe0, 0x01, 0x0a, 0x12, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65,
	0x53, 0x49, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5e, 0x0a, 0x17, 0x43, 0x61, 0x6c,
	0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x69, 0x41, 0x6e, 0x64, 0x54, 0x6f, 0x74, 0x41, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1f, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65,
	0x53, 0x49, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x49, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74,
	0x65, 0x53, 0x49, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x49, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6a, 0x0a, 0x23, 0x43, 0x61, 0x6c,
	0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x69, 0x41, 0x6e, 0x64, 0x54, 0x6f, 0x74, 0x41, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x57, 0x69, 0x74, 0x68, 0x44, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65,
	0x12, 0x1f, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x49, 0x2e, 0x43,
	0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x49, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x20, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x49, 0x2e,
	0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x49, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c, 0x2f, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c,
	0x61, 0x74, 0x65, 0x53, 0x49, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_CalculateSimpleIntrestPb_proto_rawDescOnce sync.Once
	file_CalculateSimpleIntrestPb_proto_rawDescData = file_CalculateSimpleIntrestPb_proto_rawDesc
)

func file_CalculateSimpleIntrestPb_proto_rawDescGZIP() []byte {
	file_CalculateSimpleIntrestPb_proto_rawDescOnce.Do(func() {
		file_CalculateSimpleIntrestPb_proto_rawDescData = protoimpl.X.CompressGZIP(file_CalculateSimpleIntrestPb_proto_rawDescData)
	})
	return file_CalculateSimpleIntrestPb_proto_rawDescData
}

var file_CalculateSimpleIntrestPb_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_CalculateSimpleIntrestPb_proto_goTypes = []interface{}{
	(*CalculateSIRequest)(nil),  // 0: CalculateSI.CalculateSIRequest
	(*CalculateSIResponse)(nil), // 1: CalculateSI.CalculateSIResponse
}
var file_CalculateSimpleIntrestPb_proto_depIdxs = []int32{
	0, // 0: CalculateSI.CalculateSIService.CalculateSiAndTotAmount:input_type -> CalculateSI.CalculateSIRequest
	0, // 1: CalculateSI.CalculateSIService.CalculateSiAndTotAmountWithDeadline:input_type -> CalculateSI.CalculateSIRequest
	1, // 2: CalculateSI.CalculateSIService.CalculateSiAndTotAmount:output_type -> CalculateSI.CalculateSIResponse
	1, // 3: CalculateSI.CalculateSIService.CalculateSiAndTotAmountWithDeadline:output_type -> CalculateSI.CalculateSIResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_CalculateSimpleIntrestPb_proto_init() }
func file_CalculateSimpleIntrestPb_proto_init() {
	if File_CalculateSimpleIntrestPb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_CalculateSimpleIntrestPb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculateSIRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CalculateSimpleIntrestPb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculateSIResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_CalculateSimpleIntrestPb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_CalculateSimpleIntrestPb_proto_goTypes,
		DependencyIndexes: file_CalculateSimpleIntrestPb_proto_depIdxs,
		MessageInfos:      file_CalculateSimpleIntrestPb_proto_msgTypes,
	}.Build()
	File_CalculateSimpleIntrestPb_proto = out.File
	file_CalculateSimpleIntrestPb_proto_rawDesc = nil
	file_CalculateSimpleIntrestPb_proto_goTypes = nil
	file_CalculateSimpleIntrestPb_proto_depIdxs = nil
}
